insert into user values(1,sysdate(),'AB')
insert into user values(2,sysdate(),'Jack')
insert into user values(3,sysdate(),'Ryan')
insert into post values(1,'First post',1)
insert into post values(2,'Second post',1)